### ISSUE TITLE
State being updated on window resize, context isn't.

### ISSUE THREAD

**Issue by jonathanpuc** [DomainGroupOSS/react-media-query-hoc#18] opened 2018-05-24 23:53 UTC
Hello,

I have a Component that is wrapped by the withMedia HOC.

When I resize the window, I can see that the MediaQueryProvider's state is currently updating to the correct media device, but the context of the withMedia HOC is not.

In order for the wrapped components and withMediaHOC to reflect the right device in context/props, I have to refresh the page.

I'm currently using React 16.

Here is how I'm using the MediaQueryProvider

![screen shot 2018-05-25 at 9 50 32 am](https://user-images.githubusercontent.com/26730919/40519165-7bcb3cd6-6001-11e8-8035-aaf1efbf42ee.png)

**Comment by jooj123** [comment] 2018-05-25 00:05
Thanks for the report @jonathanpuc 

Can you supply me with a JsFiddle / codepen etc so i can see what the issue is with your use case

Also what version of `react-media-query-hoc` are you on ?

**Comment by jonathanpuc** [comment] 2018-05-25 00:16
Thanks for the swifty response @jooj123, I tried something different.

Initially I had a component that was wrapped with a withMedia HOC, this component was a few levels deep within the Compare component as you can see in the screenshot provided in my first post.

I tried instead wrapping one of the main components rendered by the <Route/> with the withMediaHOC. In this case, QuoteScreen, now I can see it working properly.

Is there a reason why this worked?

I want the InclusionList component to have access to media info rather than having to wrap the whole Compare component, is this possible? 

Maybe the solution is for me to manually create context in the Compare component so InclusionList will have access to the correct and up to date media info?

**Comment by erikmoren** [comment] 2018-07-02 13:12
Hi, we have the same problem as @jonathanpuc and our solution was also to wrap all intermediate components with withMedia to make it work. Feels like old school prop-drilling, but it was the only way to make it work.  MediaQueryProvider's state was updated correctly, but the the child´s context did not update. All queries (phone, table, desktop etc) was 'false'. :-/

**Comment by jooj123** [comment] 2018-07-04 12:41
Sorry for the late reply @jonathanpuc @erikmoren 

Correct, how it works at the moment is that you need to wrap components with `withMedia` in order for them to gain context 

This may change in the future with the new context api - but not sure how exactly it would look yet.

@gricard suggested a few ideas here: https://github.com/DomainGroupOSS/react-media-query-hoc/issues/13 which are worth looking into a bit more

**Comment by jooj123** [comment] 2020-05-31 12:28
You can use `const media = useContext(MediaContext);` hook now - so closing this.

**Closed by jooj123** 2020-05-31 12:28 UTC
